services:
  bot-5x-btc:
    build: .
    container_name: trading-bot-5x-btc
    restart: on-failure
    env_file: .env
    environment:
      - BOT_ACCOUNT=bot-5x
      - BOT_SYMBOL=BTC
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY_5X}
      - HL_WALLET_ADDRESS=${HL_WALLET_ADDRESS_5X}
    volumes:
      - ./config:/app/config:ro

  bot-5x-gold:
    build: .
    container_name: trading-bot-5x-gold
    restart: on-failure
    env_file: .env
    environment:
      - BOT_ACCOUNT=bot-5x
      - BOT_SYMBOL=xyz:GOLD
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY_5X}
      - HL_WALLET_ADDRESS=${HL_WALLET_ADDRESS_5X}
    volumes:
      - ./config:/app/config:ro

  bot-8x-btc:
    build: .
    container_name: trading-bot-8x-btc
    restart: on-failure
    env_file: .env
    environment:
      - BOT_ACCOUNT=bot-8x
      - BOT_SYMBOL=BTC
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY_8X}
      - HL_WALLET_ADDRESS=${HL_WALLET_ADDRESS_8X}
    volumes:
      - ./config:/app/config:ro

  bot-10x-btc:
    build: .
    container_name: trading-bot-10x-btc
    restart: on-failure
    env_file: .env
    environment:
      - BOT_ACCOUNT=bot-10x
      - BOT_SYMBOL=BTC
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY_10X}
      - HL_WALLET_ADDRESS=${HL_WALLET_ADDRESS_10X}
    volumes:
      - ./config:/app/config:ro
